* basically...
** it's like this
** rem is relative to px font-size of *root* ("html" element, almost "body")
*** When using rem units, the pixel size they translate to depends on the font size of the root element of the page, i.e. the html element. That root font size is multiplied by whatever number you’re using with your rem unit.
** em is relative to px font-size of the same element/tag where they're used (*btw* not parent)
*** When using em units, the pixel value you end up with is a multiplication of the font size on the element being styled. 
** (this guide https://webdesign.tutsplus.com/tutorials/comprehensive-guide-when-to-use-em-vs-rem--cms-23984)
*** lots of "px" font sizes but em/rem for the other thangs (to derive from font size)? why not font em?
*** does em as font become the relative reference for child-element "em"?
** detail w/ rem
*** "Some designers use rem based layouts in conjunction with a fixed px unit font-size setting on the html element. This is typically done so that a change of font size on the html element can scale overall the design up or down."
*** "I strongly advise against this as it overrides the font size the html element inherits from the user’s browser settings. Hence this prevents the settings from having any effect, and removes the user’s ability to optimize for best viewing."
